# Generated by Django 4.1.4 on 2022-12-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
