# Generated by Django 4.1.4 on 2022-12-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformapp', '0002_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Ваша фотография'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название вашего изображения'),
        ),
    ]
