# Generated by Django 4.1.4 on 2023-01-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformapp', '0004_alter_image_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
