# Generated by Django 4.1.4 on 2023-01-12 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformapp', '0005_alter_image_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='data_download',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_people',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15, message='Максимальное количество пользователей в комнате 15')], verbose_name='Количество людей в комнате'),
        ),
    ]
