# Generated by Django 4.1.4 on 2023-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformapp', '0008_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='session',
            field=models.TextField(blank=True, null=True),
        ),
    ]
