# Generated by Django 4.1.4 on 2023-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformapp', '0009_image_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Ваша фотография'),
        ),
    ]
