# Generated by Django 4.1.4 on 2023-01-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformapp', '0011_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data_download',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
